### ISSUE TITLE
Cannot import into gulp file

### ISSUE THREAD

**Issue by mbeckenbach** [ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator.Gulp#1]
var poco = require('fluffy-spoon.javascript.csharp-to-typescript-generator.gulp');

Error: Cannot find module 'fluffy-spoon.javascript.csharp-to-typescript-generator.gulp'
    at Function.Module._resolveFilename (module.js:325:15)

**Comment by ffMathy** [comment]
Hmmm, seems some corruption in the package definition. Will take a look soon! Right now I'm busy with this branch on the emitter itself: https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator/tree/typescript-compiler-service

**Comment by tomborysiak** [comment]
The package only includes the .ts file so it needs to be compiled before you run the gulp file

**Comment by ffMathy** [comment]
Ah perfect. I don't have much time at the moment. Care to make a pull request?

**Comment by ffMathy** [comment]
This has been fixed.
